import EjsTemplateRenderer from "../lib/EjsTemplateRenderer";
import FileManager from "../lib/FileManager";
import path from "path";
import fs from "fs/promises";

export interface Property {
  name: string;
  type: string;
}

export interface FileToGenerate {
  templateName: string;
  outputFileName: string;
  outputPath: string;
}

interface ExtraData {
  entities: { name: string }[];
}

export interface GenerationConfig {
  entityName: string;
  properties: Property[];
  filesToGenerate: FileToGenerate[];
}

export class FileGeneratorApp {
  private readonly renderer: EjsTemplateRenderer;
  private readonly fileManager: FileManager;

  constructor(
    private readonly templatesDir: string,
    private readonly outputBaseDir: string
  ) {
    this.renderer = new EjsTemplateRenderer(templatesDir);
    this.fileManager = new FileManager();
  }

  /**
   * Generates all files based on the list of settings provided.
   */
  public async generate(
    configs: GenerationConfig[],
    extraData?: ExtraData
  ): Promise<void> {
    for (const config of configs) {
      const { entityName, properties, filesToGenerate } = config;

      for (const file of filesToGenerate) {
        const templateFile = file.templateName.endsWith(".ejs")
          ? file.templateName
          : `${file.templateName}.ejs`;

        const outputPath = path.join(
          this.outputBaseDir,
          file.outputPath,
          file.outputFileName
        );

        const data = {
          entityName,
          properties,
          ...(extraData || {}),
        };

        try {
          console.log(`🔧 Generating: ${outputPath} from ${templateFile}...`);
          const content = await this.renderer.render(templateFile, data);
          await this.fileManager.writeFile(outputPath, content);
          console.log(`✅ File saved: ${outputPath}`);
        } catch (error: any) {
          console.error(`❌ Error generating ${outputPath}:`, error.message);
          throw error;
        }
      }
    }
  }

  /**
   * Generates all standard application files
   */
  public async generateDefaultFiles(): Promise<void> {
    const defaultFiles = [
      {
        templateName: "package-template.ejs",
        outputFileName: "package.json",
        outputPath: "",
        data: {
          name: "Project",
          version: "1.0.0",
          description: "Project generated by CRUDius",
          main: "src/index.ts",
          scripts: {
            start: "tsx src/index.ts",
            build: "tsc",
          },
          dependencies: {
            express: "^4.17.1",
          },
          devDependencies: {
            typescript: "^4.5.4",
            "@types/node": "^16.11.7",
            "@types/express": "^4.17.13",
            sqlite3: "^5.1.7",
            tsx: "^4.16.2",
          },
        },
      },
      {
        templateName: "server-template.ejs",
        outputFileName: "server.ts",
        outputPath: "src",
        data: {},
      },
      {
        templateName: "app-template.ejs",
        outputFileName: "app.ts",
        outputPath: "src",
        data: {},
      },
    ];

    for (const file of defaultFiles) {
      const outputFullPath = path.join(
        this.outputBaseDir,
        file.outputPath,
        file.outputFileName
      );
      try {
        await fs.access(outputFullPath);
        console.log(`File already exists: ${outputFullPath}`);
      } catch (error) {
        console.log(`Generating default file: ${outputFullPath}`);
        const content = await this.renderer.render(
          file.templateName,
          file.data
        );
        await this.fileManager.writeFile(outputFullPath, content);
      }
    }
  }
}
