import path from "path";
import EjsTemplateRenderer from "../lib/EjsTemplateRenderer";

/**
 * Generates all standard application files
 */
export class GeneratorDefault {
  private readonly renderer: EjsTemplateRenderer;

  constructor(private readonly templatesDir: string) {
    this.renderer = new EjsTemplateRenderer(templatesDir);
  }
  /**
   *
   * @returns generate default files for typescript
   */
  public async generateTypescript(): Promise<GeneratedFile[]> {
    return this.generateDefaultFiles([
      {
        templateName: "package-template.ejs",
        outputFileName: "package.json",
        outputPath: "",
        data: {
          name: "Project",
          version: "1.0.0",
          description: "Project generated by CRUDius",
          dependencies: {
            express: "^4.17.1",
            "http-status-codes": "^2.2.0",
            knex: "^3.1.0",
            pg: "^8.12.0",
            yup: "^0.32.11",
            dotenv: "^16.0.1",
            "swagger-ui-express": "^5.0.1",
            "swagger-jsdoc": "^6.2.8",
          },
          devDependencies: {
            typescript: "^4.5.4",
            "ts-node": "^10.9.2",
            "@types/node": "^16.18.126",
            "@types/express": "^4.17.13",
            sqlite3: "^5.1.7",
            prettier: "^3.7.4",
            tsx: "^4.16.2",
            "@types/pg": "^8.11.6",
            "@typescript-eslint/eslint-plugin": "^5.30.6",
            "@typescript-eslint/parser": "^5.30.6",
            eslint: "^8.19.0",
          },
        },
      },
      {
        templateName: "server-template.ejs",
        outputFileName: "server.ts",
        outputPath: "src",
        data: {},
      },
      {
        templateName: "app-template.ejs",
        outputFileName: "app.ts",
        outputPath: "src",
        data: {},
      },
      {
        templateName: "index-knex.ejs",
        outputFileName: "index.ts",
        outputPath: "src/database/knex",
        data: {},
      },
      {
        templateName: "Environment-knex.ejs",
        outputFileName: "Environment.ts",
        outputPath: "src/database/knex",
        data: {},
      },
      {
        templateName: "sqlite-empty.ejs",
        outputFileName: "database.sqlite",
        outputPath: "",
        data: {},
      },
      {
        templateName: "swagger-template.ejs",
        outputFileName: "swagger.ts",
        outputPath: "src/config",
        data: {},
      },
      {
        templateName: "types-template-swagger.ejs",
        outputFileName: "swagger.d.ts",
        outputPath: "src/database/@types",
        data: {},
      },
      {
        templateName: "tsconfig-template.ejs",
        outputFileName: "tsconfig.json",
        outputPath: "",
        data: {},
      },
      {
        templateName: "knexfile.ejs",
        outputFileName: "knexfile.ts",
        outputPath: "",
        data: {},
      },
    ]);
  }

  public async generateJavascript(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  public async generatePHP(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  public async generateJava(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  /**
   *
   * @param files
   * @returns return files generate basead at script
   */
  private async generateDefaultFiles(files: any[]): Promise<GeneratedFile[]> {
    const results: GeneratedFile[] = [];

    try {
      for (const file of files) {
        const relativePath = path.join(file.outputPath, file.outputFileName);
        console.log(`Generating default file: ${relativePath}`);

        const content = await this.renderer.render(
          file.templateName,
          file.data
        );

        results.push({ path: relativePath, content });
      }

      return results;
    } catch (error: any) {
      console.error("Error while generating default files:", error.message);
      return [];
    }
  }
}
