import path from "path";
import EjsTemplateRenderer from "../lib/EjsTemplateRenderer";

/**
 * Generates all standard application files
 */
export class GeneratorDefault {
  private readonly renderer: EjsTemplateRenderer;

  constructor(private readonly templatesDir: string) {
    this.renderer = new EjsTemplateRenderer(templatesDir);
  }
/**
 * 
 * @returns generate default files for typescript
 */
  public async generateTypescript(): Promise<GeneratedFile[]> {
    return this.generateDefaultFiles([
      {
        templateName: "package-template.ejs",
        outputFileName: "package.json",
        outputPath: "",
        data: {
          name: "Project",
          version: "1.0.0",
          description: "Project generated by CRUDius",
          main: "src/app.ts",
          scripts: {
            start: "tsx src/app.ts",
            build: "tsc",
          },
          dependencies: {
            express: "^4.17.1",
          },
          devDependencies: {
            typescript: "^4.5.4",
            "@types/node": "^16.11.7",
            "@types/express": "^4.17.13",
            sqlite3: "^5.1.7",
            tsx: "^4.16.2",
          },
        },
      },
      {
        templateName: "server-template.ejs",
        outputFileName: "server.ts",
        outputPath: "src",
        data: {},
      },
      {
        templateName: "app-template.ejs",
        outputFileName: "app.ts",
        outputPath: "src",
        data: {},
      },
    ]);
  }

  public async generateJavascript(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  public async generatePHP(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  public async generateJava(): Promise<GeneratedFile[]> {
    // To be implemented
    return [];
  }

  private async generateDefaultFiles(files: any[]): Promise<GeneratedFile[]> {
    const results: GeneratedFile[] = [];

    try {
      for (const file of files) {
        const relativePath = path.join(file.outputPath, file.outputFileName);
        console.log(`Generating default file: ${relativePath}`);

        const content = await this.renderer.render(
          file.templateName,
          file.data
        );

        results.push({ path: relativePath, content });
      }

      return results;
    } catch (error: any) {
      console.error("Error while generating default files:", error.message);
      return [];
    }
  }
}
